n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(n1)))
print('Só tem espaçõs?', n1.isspace())
print('É um número?', n1.isnumeric())
print('É alfabético?', n1.isalpha())
print('é alfanumérico?', n1.isalnum())
print('Esta em maiúsculas?', n1.isupper())
print('Está em minúsculas?', n1.islower())
print('Está capitalizada?', n1.istitle())
